version: "3.8"

services:
  # Backend API - Development
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=vhk-12r.database.windows.net;Database=HelloWorld;User=HelloWorld;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    ports:
      - "5000:80"
    volumes:
      - ./backend:/app
    networks:
      - app-network
    profiles: ["dev"]

  # Frontend - Development
  frontend-dev:
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-svelte:/app
      - /app/node_modules
    environment:
      - PUBLIC_API_URL=http://localhost:5000/
    depends_on:
      - backend-dev
    profiles: ["dev"]

  # Backend API - Production
  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=vhk-12r.database.windows.net;Database=HelloWorld;User=HelloWorld;Password=${DB_PASSWORD};TrustServerCertificate=True;
    restart: always
    profiles: ["prod"]
    networks:
      - app-network

  # Frontend - Production
  frontend-prod:
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile
    ports:
      - "8099:80"
    environment:
      - API_URL=http://backend-prod
    depends_on:
      - backend-prod
    restart: always
    profiles: ["prod"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
